services:
  basic-project:
    image: basic-project
    build:
      context: .
      args:
        BASE_IMAGE: 'basic-project-dev:0.1'
    tty: true
    working_dir: /home/${USER}/project
    volumes:
      - ./:/home/${USER}/project
