name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Base Image
      run: docker build ./dev --file Dockerfile --tag basic-project-dev:$(date +%s)

    - name: Build the User Image
      run: docker build . --file Dockerfile --tag basic-project:$(date +%s)
